<?php echo $this->action('top','proyecto','default');?>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero','action'=>'index'),'',true);?>">Tablero</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'index'),'',true);?>">Proyectos</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'index'),'',true);?>">Proyecto: <?php echo $this->datos->nombre_empresa;?></a>  <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'modulo','id'=>$this->modulos->id_empresa),'',true);?>">Modulos</a>  <span class="divider">/</span></li>    
    <li class="active">Componentes de modulo <strong><?php echo $this->modulos->nombre_modulo;?></strong></li>
</ul>
<div class="page-header">     
    <h3>Componentes</h3>
    <h3><small>Listado de componentes que se pueden asociar a un modulo</small></h3>
</div>
<div class="span4">
    <div class="well">
        <h4>Formulario componente</h4>
        <?php echo $this->formulario;?>
    </div>
</div>
<div class="span7">
    <?php if($this->error) :?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <h2>¡Noooooooooooooooo!</h2>Mira el listado ya fue agregado este componente!! <strong>#FAIL</strong>
        </div> 
    <?php elseif($this->exito) :?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <h2>¡Pichichi!</h2> Se completo exitosamente la operación. <em>¿No haz pensado en postular a Google?</em>
        </div>         
    <?php endif;?>
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>Nombre</th>
                <th class="span2">Acciones</th>            
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->componente as $retorno) :?>            
            <tr>
                <td><?php echo $retorno->nombre_componente;?></td>
                <td>
                    <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="icon-pencil"></i> Opciones <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'eliminacomponente','id'=>$this->modulos->id_empresa,'idmodulo'=>$this->modulos->id_modulo,'idcomponente'=>$retorno->id_componente),'',true);?>"><i class="icon-trash"></i> Eliminar</a></li>
                        <?php if($retorno->id_componente == 1):?>
                            <li><a href="#myModal" data-toggle="modal"><i class="icon-camera"></i> Tamaños</a></li>
                        <?php endif;?>
                    </ul>
                    </div>                       
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>   
<div class="modal" id="myModal" style="display: none">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">×</a>
        <h3>Modificaciones tamaño de imágenes</h3>
        <h3><small>Esta opción se vera reflejada al momento de agregar una fotografía en algun modulo que tenga la componente</small></h3>
    </div>
    <div class="modal-body">
        <?php echo $this->formulario_tamano;?>
        <div class="clearfix"></div>
    </div>
</div>  