<?php echo $this->action('top','proyecto','default');?>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero','action'=>'index'),'',true);?>">Tablero</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'index'),'',true);?>">Proyectos</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'index'),'',true);?>">Proyecto: <?php echo $this->datos->nombre_empresa;?></a>  <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'modulo','id'=>$this->modulos->id_empresa),'',true);?>">Modulos</a>  <span class="divider">/</span></li>    
    <li class="active">Componentes de modulo <strong><?php echo $this->modulos->nombre_modulo;?></strong></li>
</ul>
<div class="page-header">     
    <h3>Componentes</h3>
    <h3><small>Listado de componentes que se pueden asociar a un modulo</small></h3>
</div>
<div class="span4">
    <div class="well">
        <h4>Formulario componente</h4>
        <?php echo $this->formulario;?>
    </div>
</div>
<div class="span7">
    <?php if($this->error) :?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <h2>¡Noooooooooooooooo!</h2>Mira el listado ya fue agregado este componente!! <strong>#FAIL</strong>
        </div> 
    <?php elseif($this->exito) :?>
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <h2>¡Pichichi!</h2> Se completo exitosamente la operación. <em>¿No haz pensado en postular a Google?</em>
        </div>         
    <?php endif;?>
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>Nombre</th>
                <th class="span1">Acciones</th>            
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->componente as $retorno) :?>            
            <tr>
                <td><?php echo $retorno->nombre_componente;?></td>
                <td>
                    <a class="btn btn-danger btn-mini" href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'eliminacomponente','id'=>$this->modulos->id_empresa,'idmodulo'=>$this->modulos->id_modulo,'idcomponente'=>$retorno->id_componente),'',true);?>">Borrar</a>                
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>