<?php echo $this->action('top','proyecto','default');?>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero','action'=>'index'),'',true);?>">Tablero</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'index'),'',true);?>">Proyectos</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'index'),'',true);?>">Proyecto: <?php echo $this->datos->nombre_empresa;?></a>  <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'modulo','id'=>$this->modulos->id_empresa),'',true);?>">Modulos</a>  <span class="divider">/</span></li>
    <li class="active">Campos de <strong><?php echo $this->modulos->nombre_modulo;?></strong></li>
</ul>
<div class="page-header">
    <div class="alert alert-block">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <h2>¡Ojo!</h2>Recuerda crear un campo llamado <strong>Nombre</strong> en todos los módulos del proyecto. Esto nos ayudará a crear sitios con <a target="_blank" href="http://es.wikipedia.org/wiki/URL_sem%C3%A1ntica">url amigables</a> y con fácil indexación de contenidos para Google.
    </div>      
    <h3>Campos del modulo</h3>
    <h3><small><strong>El listado de campos correspondientes al módulo</strong>.<br />En esta sección se configuran los parámetros que serán luego interpretados por el CMS del cliente.</small></h3>
</div>
<div class="span4">
    <div class="well">
        <h4>Formulario ingreso de campo</h4>
        <?php echo $this->formulario;?>
    </div>
</div>
<div class="span7">   
    <?php if($this->error) :?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <h2>¡Avispate!</h2>Este campo ya fue creado anteriormente.
        </div> 
    <?php elseif($this->error_campo) :?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <h2>¡Ups!</h2>No se pudo completar la operación. Verifica manualmente en la base de datos <strong><?php echo $this->datos->basededatos_empresa;?></strong> en la tabla <strong>#<?php echo $this->modulos->nombre_modulo_slug;?></strong>.
        </div>    
    <?php elseif($this->exito) :?>   
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <h2>¡Seco!</h2>Se completo exitosamente la operación solicitada.</strong>
        </div>        
    <?php endif;?>    
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Listado</th>            
                <th>Tipo</th>
                <th>Validación</th>
                <th>Estado</th>
                <th class="span1">Acciones</th>            
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->campos as $retorno) :?>            
            <tr>
                <td><?php echo $retorno->nombre_campo;?></td>
                <td><?php echo $retorno->listado_campo;?></td>
                <td><?php echo $retorno->nombre_tipo;?></td>
                <td><?php echo $retorno->nombre_validacion;?></td>
                <td><?php echo $retorno->nombre_estado;?></td>
                <td>
                    <?php if($retorno->borrar) :?>
                    <a class="btn btn-danger btn-mini" href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'eliminacampo','id'=>$this->modulos->id_empresa,'idmodulo'=>$this->modulos->id_modulo,'idcampo'=>$retorno->id_campo),'',true);?>"><i class="icon-trash icon-white"></i></a>                
                    <?php endif;?>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>   
    <?php if($this->boton) :?>
        <a class="btn btn-success btn-large" href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'bdmoduloactualiza','id'=>$this->modulos->id_empresa,'idmodulo'=>$this->modulos->id_modulo),'',true);?>"><strong>Actualizar estructura</strong></a>
    <?php else :?>        
        <a class="btn btn-success btn-large" href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'bdmodulocrear','id'=>$this->modulos->id_empresa,'idmodulo'=>$this->modulos->id_modulo),'',true);?>"><strong>Crear estructura</strong></a>
    <?php endif;?>
</div>