<?php echo $this->action('top','proyecto','default');?>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero','action'=>'index'),'',true);?>">Tablero</a> <span class="divider">/</span></li>
    <li class="active">Proyectos</li>
</ul>
<a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'crear'),'',true);?>" class="btn btn-success btn-small pull-right abajo-bottom"><strong>CREAR PROYECTO</strong></a>
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Servidor</th>
            <th>Base de datos</th>
            <th>Usuario</th>
            <th>Clave</th>
            <th>Url</th>
            <th class="span4">Acciones</th>            
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->datos as $retorno) :?>            
        <tr>
            <td><?php echo $retorno->nombre_empresa;?></td>
            <td><?php echo $retorno->servidor_empresa;?></td>
            <td><?php echo $retorno->basededatos_empresa;?></td>
            <td><?php echo $retorno->usuario_empresa;?></td>
            <td><?php echo $retorno->clave_empresa;?></td>
            <td><i class="icon-home"></i> <a href="<?php echo $retorno->url_empresa;?>" target="_blank">Ver proyecto</a></td>
            <td>
                <div class="btn-group">                
                    <a href="#" class="btn dropdown-toggle" data-toggle="dropdown">
                        Proyecto <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="icon-pencil"></i> Editar</a></li>
                    </ul>   
                    <a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'modulo','id'=>$retorno->id_empresa),'',true);?>" class="btn"><i class="icon-folder-open"></i> Módulos</a> 
                    <a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'relacion','id'=>$retorno->id_empresa),'',true);?>" class="btn"><i class="icon-refresh"></i> Relaciones</a>    
                </div>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>