<?php echo $this->action('top','usuario','default');?>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero','action'=>'index'),'',true);?>">Tablero</a> <span class="divider">/</span></li>
    <li class="active">Usuarios sistema</li>
</ul>
<a href="<?php echo $this->url(array('module'=>'default','controller'=>'usuario','action'=>'crear'),'',true);?>" class="btn btn-success btn-small pull-right abajo-bottom"><strong>CREAR USUARIO</strong></a>
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>Nombre</th>
            <th class="span3">Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->datos as $retorno) :?>            
        <tr>
            <td><?php echo $retorno->email_usuario;?></td>
            <td>
                <a href="<?php echo $this->url(array('module'=>'default','controller'=>'usuario','action'=>'editar','id'=>$retorno->id_usuario),"",true);?>" class="btn btn-mini"><i class="icon-pencil"></i> Editar</a>
                <a href="<?php echo $this->url(array('module'=>'default','controller'=>'usuario','action'=>'eliminar','id'=>$retorno->id_usuario),"",true);?>" class="btn btn-mini"><i class="icon-trash"></i> Eliminar</a>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>