<?php echo $this->action('top','tablero','default');?>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero','action'=>'index'),'',true);?>">Tablero</a> <span class="divider">/</span></li>
    <li class="active">Actualizaciones</li>
</ul>
<h3>Actualizaciones</h3>
<h3><small>Listado de actualizaciones del sistema</small></h3>
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th class="span1"></th>
            <th>Fecha</th>
            <th>Autor</th>
            <th>Comentario</th>           
        </tr>
    </thead>
    <tbody>         
        <tr>
            <td>1</td>
            <td>14-05-2012</td>
            <td>Jonathan</td>
            <td>Creación de PYME</td>
        </tr>
        <tr>
            <td>2</td>
            <td>07-06-2012</td>
            <td>Jonathan</td>
            <td>
                Creación de mantenedores del sistema (agregar y eliminar), tales como:<br />
                <ul>
                    <li><strong>Generales</strong>
                        <ul>
                            <li>Estado</li>
                            <li>Idiomas</li>
                            <li>Componentes</li>
                        </ul>    
                    </li>   
                    <li><strong>Modulos</strong>
                        <ul>
                            <li>Cardinalidad</li>
                            <li>Relación</li>
                        </ul>    
                    </li> 
                    <li><strong>#Campo</strong>
                        <ul>
                            <li>Tipos</li>
                            <li>Validaciones</li>
                        </ul>    
                    </li>                     
                    <li><strong>#Usuario</strong>
                        <ul>
                            <li>Tipos</li>
                        </ul>    
                    </li>                     
                </ul>
            </td>
        </tr>
    </tbody>
</table>