<?php echo $this->doctype();echo "\n"; ?>
<html>
<head>   
<?php echo $this->headTitle();echo "\n"; ?>
<?php echo $this->headMeta();echo "\n"; ?>
<?php echo $this->headLink();echo "\n"; ?>
<?php echo $this->headScript();echo "\n"; ?>  
</head>
<body>
    <div class="container">
        <div class="row abajo">
            <div class="span4">
                <img alt="" src="http://placehold.it/200x50">
            </div>
            <div class="span8">
                <div class="row pull-right">
                    ¡ Bienvenido ! <strong><?php echo $this->email_usuario;?></strong> |
                    <a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero','action'=>'cerrar'),'',true);?>">Cerrar sesión</a>
                </div>
            </div>
        </div>
        <div class="navbar abajo">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav">
                        <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero','action'=>'index'),'',true);?>">Tablero</a></li>
                        <li class="divider-vertical"></li>                         
                        <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'proyecto','action'=>'index'),'',true);?>">Proyectos</a></li>
                        <li class="divider-vertical"></li>                         
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Mantenedores<b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-header">Generales</li>     
                                <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'mantenedor','action'=>'estado'),'',true);?>"><i class="icon-list-alt"></i> Estados</a></li>
                                <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'mantenedor','action'=>'idioma'),'',true);?>"><i class="icon-list-alt"></i> Idiomas</a></li>
                                <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'mantenedor','action'=>'componente'),'',true);?>"><i class="icon-list-alt"></i> Componentes</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">Modulos</li>
                                <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'mantenedor','action'=>'cardinalidad'),'',true);?>"><i class="icon-list-alt"></i> Cardinalidad</a></li>                                
                                <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'mantenedor','action'=>'relacion'),'',true);?>"><i class="icon-list-alt"></i> Relación</a></li>                                
                                <li class="divider"></li>
                                <li class="nav-header">#campo</li>
                                <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'mantenedor','action'=>'tipos'),'',true);?>"><i class="icon-list-alt"></i> Tipos</a></li>
                                <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'mantenedor','action'=>'validacion'),'',true);?>"><i class="icon-list-alt"></i> Validaciones</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">#usuario</li>
                                <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'mantenedor','action'=>'usuariotipo'),'',true);?>"><i class="icon-list-alt"></i> Tipos</a></li>
                            </ul> 
                        </li>
                        <li class="divider-vertical"></li>                         
                        <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'usuario','action'=>'index'),'',true);?>">Usuarios sistema</a></li>
                    </ul>
                </div>
            </div>            
        </div>
        <?php echo $this->layout()->content; ?>
        <div style="clear: both"></div>
        <div class="row-fluid footer">
            <div class="pull-right creditos">
                <strong>PYME</strong> 0.1 BETA - Desarrollo Área Digital - <a href="https://github.com/cijonathan/pyme/commits/master" target="_blank">Actualizaciones</a>
            </div>
        </div>
    </div>  
</body>
</html>